---
title: "snATAC ArchR initial QC report `r REGION`"
author: "Darren Cameron"
date: "`r format(Sys.time(), '%d/%m/%y')`"
output:
  html_document:
    theme: paper
---

```{r packages, echo=FALSE, include=FALSE}
library(SingleCellExperiment)
library(scater)
library(cowplot)
library(knitr)
```

snATACseq analysis with ArchR.

*** 

### Results {.tabset}

#### QC

ArchR takes the fragments file as input. This is different from Signac/Seurat which takes the filtered read matrix generated by Cell Ranger as input. 

ArchR pre-filters the cells using thresholds:

  + TSS Enrichment > 4
  + Min frags per cell > 1000

***

**Counts**

```{R, filt_cells_dropped, echo=FALSE}
knitr::kable(counts_df)
```

***

**Doublet removal**

Post-doublet removal numbers are the final cell numbers moving forward. 

```{R, doublets, echo=FALSE}
knitr::kable(doublet_df)
```

***

**Pre-filter plots**

***

**TSS enrichment vs. log10(Number of fragments) - these are the pre-filtered results**

If you want to compare these results to others studies check out page 4 of the [ArchR supplementary document](https://static-content.springer.com/esm/art%3A10.1038%2Fs41588-021-00790-6/MediaObjects/41588_2021_790_MOESM1_ESM.pdf).

```{R, pre_filt_plots, echo=FALSE}
preQC_tss_uFrag_plot <- ggAlignPlots(preQC_tss_uFrag_plot_510, preQC_tss_uFrag_plot_611,
                                     preQC_tss_uFrag_plot_993, type = "h")
```

***

**Post-filter plots**

**TSS enrichment vs. log10(Number of fragments) plot - all samples combined**

```{R, post_filt_tss_uFrag, echo=FALSE}
tss_uFrag_plot
```

*** 

**Fragment size plot**

```{R, post_filt_frag_size, echo=FALSE}
fragSize_plot
```

***

**TSS plot**

NOTE: There is a bug in the software, as all of the plots TSS plots look the same! I've added a second ridge plot below which shows the same thing.

```{R, post_filt_tss_plot, echo=FALSE}
tss_plot
```

***

**Ridge plot**

```{R, post_filt_ridge_plot, echo=FALSE, message=FALSE}
ridge_plot
```

***

#### Clusters

**Pre-batch corrected clusters**

```{R, Clusters, echo=FALSE}
ggAlignPlots(clusters_UMAP, clusters_UMAP_BySample, type = "h")
```

***

**Cell counts per cluster**

```{R, Cluster_cnts, echo=FALSE}
knitr::kable(clusters_cnts)
```

***

**Confusion Matrix**

Showing cell counts per donor in each cluster. The threshold for cluster inclusion at this stage is clusters must have at 
least 10 cells from 2 out of 3 donors to be included in downstream analyses.


```{R, Cluster_CM, echo=FALSE}
clust_CM_LSI
```

***
